### ISSUE TITLE
2D rendering inconsistencies between jit and vm

### ISSUE THREAD

**Issue by sgenoud** [mkeeter/fidget#240]
There appears to be a fundamental difference in rendering behavior between JIT and VM rendering modes. I have here an example using an elliptic arc [ellipse-arc.vm](https://github.com/user-attachments/files/18688844/ellipse-arc.vm.txt).

Using the demo CLI it renders with the jit in that way:

```
cargo run -pfidget-cli --release -- -i ./ellipse-arc.vm render2d --sdf -s 1024 --eval=jit -o ellipse-with-jit.png
```

![Image](https://github.com/user-attachments/assets/eb36d26b-7dcf-4829-b389-0ca9f05190a0)

While the VM returns this

```
cargo run -pfidget-cli --release -- -i ./ellipse-arc.vm render2d --sdf -s 1024 --eval=vm -o ellipse-with-vm.png
```

![Image](https://github.com/user-attachments/assets/59ad15c7-bfb3-44a3-aef8-135d1d9e0b47)

**Comment by mkeeter** [comment]
Two quick observations:

- This looks like a difference in interval evaluation, because `--brute` (which evaluates every single pixel) gives the same result
- In fact, JIT evaluation _is_ doing per-pixel evaluation, meaning the interval evaluator must be returning ambiguous results.  For the VM, the interval evaluator is finding empty / full regions, including incorrectly along the curve

Here's the visualization of interval evaluation results for the VM evaluator:

![Image](https://github.com/user-attachments/assets/1273f59d-ab91-434c-8eee-566cee1e1cbe)

**Comment by mkeeter** [comment]
@sgenoud can you say more about how you generated this expression?  There's a lot going on in there (trig functions, a bunch of logical functions, etc)!

**Comment by sgenoud** [comment]
Of course! I am building a higher level API in typescript to build SDFs. I generate a graph of operations that are then evaluated as a fidget tree (using a wasm compiled version of the library). To build the `.vm` file I exported the operations graph in the format you use instead.

I found this bug while implementing an [arc of ellipse primitive](https://www.shadertoy.com/view/4dyyR1). 

To find the distance to arc of ellipses you need to solve a quartic (I have tried some more iterative methods, but while good for the full ellipse I could not make them work correctly everywhere). So this is the reason of all the complex logic.

**Comment by mkeeter** [comment]
This should be fixed by #241

It's worth noting that your shape isn't friendly to interval evaluation – it often returns `NAN`, which doesn't let the evaluator prune spatial regions.  The usual cause here is an unclamped sqrt, i.e. `sqrt([-0.5, 1])` will return `[NAN, NAN]`, which will then propagate through the rest of evaluation.  If you're confident that your square root inputs are always >= 0, then consider doing `sqrt(max(.., 0))` instead.

The default renderer in `fidget-cli` will show interval evaluation results in red / green; if you're seeing only black and white, then it has used the per-pixel evaluator everywhere.

**Comment by sgenoud** [comment]
I have tested your changes. There are  improvements, but the render is still wrong (vm render here):

![Image](https://github.com/user-attachments/assets/fafc8e24-d27c-4b78-83d1-03e18225bde5).

Am I missing something?

**Comment by mkeeter** [comment]
Nope, let me take another look!

**Comment by sgenoud** [comment]
I have refactored my logic to get rid of the `NaN`, here is the file if you want to use that instead for investigations. The behavior is the same in terms of render.

[ellipse-arc-no-nan.vm.txt](https://github.com/user-attachments/files/18750720/ellipse-arc-no-nan.vm.txt)

**Comment by mkeeter** [comment]
I've got a fix for the AArch64 JIT in [this branch](https://github.com/mkeeter/fidget/tree/fix-interval-and-or), but will need to fix the x86 backend before opening a PR.

**Comment by mkeeter** [comment]
@sgenoud can you check whether #245 fixes things?  It looks correct on my machine, for both VM and JIT (AArch64) backends.

**Comment by sgenoud** [comment]
Yes, it looks good on my machine (as well as the version compiled into wasm). Thanks a lot!
